<?php

/**
 * @file
 * Hooks provided by Path Breadcrumbs module.
 */

/**
 * Expose Path Breadcrumbs settings.
 *
 * This hook is called by CTools. For this hook to work, you need
 * hook_ctools_plugin_api(). The values of this hook can be overridden
 * and reverted through the UI.
 */
function hook_path_breadcrumb_settings_info() {
  $path_breadcrumbs = array();

  $path_breadcrumb = new stdClass();
  $path_breadcrumb->api_version = 1;
  $path_breadcrumb->path_id = '1001';
  $path_breadcrumb->machine_name = 'example_breadcrumb';
  $path_breadcrumb->name = 'Example breadcrumb';
  $path_breadcrumb->path = 'node/%node';
  $path_breadcrumb->data = 'a:6:{s:6:"titles";a:3:{i:0;s:51:"1%node:content-type (%node:content-type:node-count)";i:1;s:11:"%node:title";i:2;s:19:"%node:comment-count";}s:5:"paths";a:3:{i:0;s:36:"node/%node:content-type:machine-name";i:1;s:14:"node/%node:nid";i:2;s:6:"<none>";}s:4:"home";i:1;s:12:"translatable";i:0;s:9:"arguments";a:1:{s:4:"node";a:3:{s:8:"position";i:1;s:8:"argument";s:14:"entity_id:node";s:8:"settings";a:1:{s:10:"identifier";s:8:"Node: ID";}}}s:6:"access";a:0:{}}';
  $path_breadcrumb->weight = 0;
  $path_breadcrumb->disabled = 0;

  $path_breadcrumbs[] = $path_breadcrumb;

  return $path_breadcrumbs;
}

/**
 * Respond to saving path_breadcrumbs.
 *
 * This hook is invoked after creating new path_breadcrumbs or updating
 * existing one.
 * @param object $path_breadcrumbs
 *    Object with all necessary information from saving form.
 */
function hook_path_breadcrumbs_save($path_breadcrumbs) {
  // @todo Needs function body.
}

/**
 * Respond to path_breadcrumbs deletion.
 *
 * This hook is invoked before path_breadcrumbs variant is removed from
 * the database.
 *
 * @param object $path_breadcrumbs
 */
function hook_path_breadcrumbs_delete($path_breadcrumbs) {
  // @todo Needs function body.
}

/**
 * Act on a path_breadcrumbs object is preparing for view.
 *
 * This hook is invoked before any token replacement.
 *
 * @param object $path_breadcrumbs
 *    Object with path breadcrumb variant loaded from database.
 * @param array $contexts
 *    Ctools contexts from current URL.
 * @return object $path_breadcrumbs
 */
function path_breadcrumbs_view(&$path_breadcrumbs, $contexts) {
  // @todo Needs function body.
}

/**
 * Alter breadcrumbs generated by _path_breadcrumbs_build_breadcrumbs().
 *
 * This hook is invoked after breadcrumbs were built.
 *
 * @param array $breadcrumbs
 *    Alterable array of build breadcrumbs.
 * @param object $path_breadcrumbs
 *    Unalterable object contains both processed and raw titles and paths.
 * @param array $contexts
 *    Ctools contexts from current URL.
 */
function path_breadcrumbs_view_alter(&$breadcrumbs, $path_breadcrumbs, $contexts) {
  // @todo Needs function body.
}
